[package]
name = "rust-ui-fltk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1.3.33"
rustyline = "8.1.0"
perf-event = "0.4.8"
rand = "0.8.4"
